// The games shown on the front page, in display order.
// To add a game: create games/<slug>/ with its own index.html, then add one
// entry here. Paths are relative to the repository root.
window.MINI_GAMES = [
  {
    slug: 'balloon-pop',
    name: 'Balloon Pop',
    description: 'Pop photoreal hot-air balloons over a dusk sea with a pin, dart, air rifle or slingshot.',
    path: 'games/balloon-pop/',
    image: 'games/balloon-pop/cover.jpg',
    imageAlt: 'Striped hot-air balloons drifting over a calm sea at sunset',
    tags: ['3D', 'All ages', 'Touch friendly'],
  },
  {
    slug: 'cake-cut',
    name: 'Cake Cut',
    description: 'Decorate a photoreal party cake, blow out the candles, then cut and serve slices with a knife, wire or cake sword.',
    path: 'games/cake-cut/',
    image: 'games/cake-cut/cover.jpg',
    imageAlt: 'A rainbow layer cake on a porcelain stand, cut open, with one slice served on a plate',
    tags: ['3D', 'All ages', 'Touch friendly'],
  },
  {
    slug: 'rocket-blast',
    name: 'Rocket Blast',
    description: 'Fly a happy toy rocket and blast googly-eyed toys into showers of stars and sweets. No losing, ever.',
    path: 'games/rocket-blast/',
    image: 'games/rocket-blast/cover.jpg',
    imageAlt: 'A smiling toy rocket firing golden bolts at googly-eyed toy blocks bursting into stars and sweets in a blue sky',
    tags: ['3D', 'Ages 2+', 'Touch friendly'],
  },
  {
    slug: 'garden-grow',
    name: 'Garden Grow',
    description: 'Plant seeds in a photoreal garden, water them and watch flowers bloom and butterflies arrive. Calm and bedtime-friendly.',
    path: 'games/garden-grow/',
    image: 'games/garden-grow/cover.jpg',
    imageAlt: 'A cottage garden bed at golden hour with tulips, poppies and sunflowers in bloom and a butterfly visiting',
    tags: ['3D', 'Ages 2+', 'Touch friendly'],
  },
  {
    slug: 'block-tower',
    name: 'Block Tower',
    description: 'Stack photoreal wooden toy blocks into a tower, then knock it down with a ball, a wind-up car or a wrecking ball.',
    path: 'games/block-tower/',
    image: 'games/block-tower/cover.jpg',
    imageAlt: 'A tall tower of wooden and painted toy blocks on playroom floorboards in soft window light',
    tags: ['3D', 'Ages 2+', 'Touch friendly'],
  },
  {
    slug: 'marble-run',
    name: 'Marble Run',
    description: 'Drop shiny glass marbles down photoreal marble runs that ring bells, spin wheels and loop the loop, then build your own.',
    path: 'games/marble-run/',
    image: 'games/marble-run/cover.jpg',
    imageAlt: 'Glass marbles rolling down a wooden toy marble run with a spiral funnel, a loop, a water wheel and brass bells in a sunlit playroom',
    tags: ['3D', 'Ages 2+', 'Touch friendly'],
  },
  {
    slug: 'splash-ride',
    name: 'Splash Ride',
    description: 'Steer a little boat across a sunny lagoon, a sunset lake, a canal town and a glowing night bay, with spray, splashes, dolphins and sparkle rings.',
    path: 'games/splash-ride/',
    image: 'games/splash-ride/cover.jpg',
    imageAlt: 'A white speedboat with a dolphin leaping alongside, crossing a turquoise lagoon between palm islands',
    tags: ['3D', 'Ages 2+', 'Touch friendly'],
  },
];
